spring:
  datasource:
    url: jdbc:h2:mem:library
    username: user
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true
      path: '/h2-console'